app = "yb"
kill_signal = "SIGINT"
kill_timeout = 60
[[services]]
  internal_port = 8080
  protocol = "tcp"
  script_checks = []
  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80
[mount]
source="data"
destination="/data"
